[tool.poetry]
name = "tutto-api"
version = "0.1.0"
description = ""
authors = ["rapha-pereira <raphaelpgomes1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
